[2023-04-02T03:07:11.352+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.upload_data_to_mongodb manual__2023-04-02T03:07:06.281595+00:00 [queued]>
[2023-04-02T03:07:11.359+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.upload_data_to_mongodb manual__2023-04-02T03:07:06.281595+00:00 [queued]>
[2023-04-02T03:07:11.360+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-02T03:07:11.361+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-02T03:07:11.361+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-02T03:07:11.376+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): upload_data_to_mongodb> on 2023-04-02 03:07:06.281595+00:00
[2023-04-02T03:07:11.388+0000] {standard_task_runner.py:55} INFO - Started process 694 to run task
[2023-04-02T03:07:11.396+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'upload_data_to_mongodb', 'manual__2023-04-02T03:07:06.281595+00:00', '--job-id', '416', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpwq4bjb9f']
[2023-04-02T03:07:11.397+0000] {standard_task_runner.py:83} INFO - Job 416: Subtask upload_data_to_mongodb
[2023-04-02T03:07:11.497+0000] {task_command.py:388} INFO - Running <TaskInstance: demo_dag.upload_data_to_mongodb manual__2023-04-02T03:07:06.281595+00:00 [running]> on host 0b6a9b63e384
[2023-04-02T03:07:11.723+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_dag
AIRFLOW_CTX_TASK_ID=upload_data_to_mongodb
AIRFLOW_CTX_EXECUTION_DATE=2023-04-02T03:07:06.281595+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-02T03:07:06.281595+00:00
[2023-04-02T03:07:11.725+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 36, in upload_data_to_mongodb
    host=f"mongodb+srv://{config['mongodb']['database_user']}:{config['mongodb']['database_password']}@mycluster.2gvwkvc.mongodb.net/?retryWrites=true&w=majority",
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'mongodb'
[2023-04-02T03:07:11.736+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=demo_dag, task_id=upload_data_to_mongodb, execution_date=20230402T030706, start_date=20230402T030711, end_date=20230402T030711
[2023-04-02T03:07:11.749+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 416 for task upload_data_to_mongodb ('mongodb'; 694)
[2023-04-02T03:07:11.769+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-02T03:07:11.783+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
