[2023-04-04T03:19:53.472+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T03:19:47.186895+00:00 [queued]>
[2023-04-04T03:19:53.478+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T03:19:47.186895+00:00 [queued]>
[2023-04-04T03:19:53.478+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T03:19:53.479+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-04T03:19:53.479+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T03:19:53.487+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): upload_to_azure_sql> on 2023-04-04 03:19:47.186895+00:00
[2023-04-04T03:19:53.492+0000] {standard_task_runner.py:55} INFO - Started process 92 to run task
[2023-04-04T03:19:53.495+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'demo_dag2', 'upload_to_azure_sql', 'manual__2023-04-04T03:19:47.186895+00:00', '--job-id', '456', '--raw', '--subdir', 'DAGS_FOLDER/test_dag2.py', '--cfg-path', '/tmp/tmpyuu9w8l4']
[2023-04-04T03:19:53.496+0000] {standard_task_runner.py:83} INFO - Job 456: Subtask upload_to_azure_sql
[2023-04-04T03:19:53.548+0000] {task_command.py:388} INFO - Running <TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T03:19:47.186895+00:00 [running]> on host eb9f63ec844e
[2023-04-04T03:19:53.622+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_dag2
AIRFLOW_CTX_TASK_ID=upload_to_azure_sql
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T03:19:47.186895+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-04T03:19:47.186895+00:00
[2023-04-04T03:19:54.446+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag2.py", line 51, in upload_to_azure_sql
    'Driver={ODBC Driver 18 for SQL Server};Server=tcp:cs779-server.database.windows.net,1433;Database=cs779;Uid=epoch;Pwd={your_password_here};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;'
pyodbc.InterfaceError: ('28000', "[28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user 'epoch'. (18456) (SQLDriverConnect)")
[2023-04-04T03:19:54.504+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=demo_dag2, task_id=upload_to_azure_sql, execution_date=20230404T031947, start_date=20230404T031953, end_date=20230404T031954
[2023-04-04T03:19:54.551+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 456 for task upload_to_azure_sql (('28000', "[28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user 'epoch'. (18456) (SQLDriverConnect)"); 92)
[2023-04-04T03:19:54.599+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-04T03:19:54.637+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
