[2023-04-04T03:26:18.413+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T03:26:11.597344+00:00 [queued]>
[2023-04-04T03:26:18.423+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T03:26:11.597344+00:00 [queued]>
[2023-04-04T03:26:18.424+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T03:26:18.425+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-04T03:26:18.425+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-04T03:26:18.435+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): upload_to_azure_sql> on 2023-04-04 03:26:11.597344+00:00
[2023-04-04T03:26:18.442+0000] {standard_task_runner.py:55} INFO - Started process 250 to run task
[2023-04-04T03:26:18.446+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'demo_dag2', 'upload_to_azure_sql', 'manual__2023-04-04T03:26:11.597344+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/test_dag2.py', '--cfg-path', '/tmp/tmpeh6u67wk']
[2023-04-04T03:26:18.447+0000] {standard_task_runner.py:83} INFO - Job 460: Subtask upload_to_azure_sql
[2023-04-04T03:26:18.512+0000] {task_command.py:388} INFO - Running <TaskInstance: demo_dag2.upload_to_azure_sql manual__2023-04-04T03:26:11.597344+00:00 [running]> on host eb9f63ec844e
[2023-04-04T03:26:18.562+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_dag2
AIRFLOW_CTX_TASK_ID=upload_to_azure_sql
AIRFLOW_CTX_EXECUTION_DATE=2023-04-04T03:26:11.597344+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-04T03:26:11.597344+00:00
[2023-04-04T03:26:20.247+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag2.py", line 151, in upload_to_azure_sql
    row.scores_away_total
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 33 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[2023-04-04T03:26:20.278+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=demo_dag2, task_id=upload_to_azure_sql, execution_date=20230404T032611, start_date=20230404T032618, end_date=20230404T032620
[2023-04-04T03:26:20.297+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 460 for task upload_to_azure_sql (('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 33 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)'); 250)
[2023-04-04T03:26:20.351+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-04T03:26:20.381+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
