[2023-04-02T03:42:59.753+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag.upload_to_mongo_db manual__2023-04-02T03:42:55.404731+00:00 [queued]>
[2023-04-02T03:42:59.758+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag.upload_to_mongo_db manual__2023-04-02T03:42:55.404731+00:00 [queued]>
[2023-04-02T03:42:59.759+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-02T03:42:59.759+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-02T03:42:59.759+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-02T03:42:59.767+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): upload_to_mongo_db> on 2023-04-02 03:42:55.404731+00:00
[2023-04-02T03:42:59.773+0000] {standard_task_runner.py:55} INFO - Started process 1550 to run task
[2023-04-02T03:42:59.778+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'demo_dag', 'upload_to_mongo_db', 'manual__2023-04-02T03:42:55.404731+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpb6n5x_u0']
[2023-04-02T03:42:59.778+0000] {standard_task_runner.py:83} INFO - Job 428: Subtask upload_to_mongo_db
[2023-04-02T03:42:59.846+0000] {task_command.py:388} INFO - Running <TaskInstance: demo_dag.upload_to_mongo_db manual__2023-04-02T03:42:55.404731+00:00 [running]> on host 0b6a9b63e384
[2023-04-02T03:42:59.915+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=demo_dag
AIRFLOW_CTX_TASK_ID=upload_to_mongo_db
AIRFLOW_CTX_EXECUTION_DATE=2023-04-02T03:42:55.404731+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-02T03:42:55.404731+00:00
[2023-04-02T03:43:00.755+0000] {logging_mixin.py:137} INFO - <class 'dict'>
[2023-04-02T03:43:00.756+0000] {logging_mixin.py:137} INFO - {'ResponseMetadata': {'RequestId': '7BEZ9DA4Q15145QQ', 'HostId': 'q6+FwAd/yCm2xKrxDqp0DID1JhKYA2TmoLaqmt1+07YrkuV3iw7Mx+Bb5ZnZn1Fm9Mt4Ix9xcTk=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'q6+FwAd/yCm2xKrxDqp0DID1JhKYA2TmoLaqmt1+07YrkuV3iw7Mx+Bb5ZnZn1Fm9Mt4Ix9xcTk=', 'x-amz-request-id': '7BEZ9DA4Q15145QQ', 'date': 'Sun, 02 Apr 2023 03:42:52 GMT', 'last-modified': 'Sun, 02 Apr 2023 03:42:49 GMT', 'etag': '"cde1715b3cbc30cc963e7a1c03c06554"', 'x-amz-server-side-encryption': 'AES256', 'x-amz-version-id': 'KdRWpuBAP2gIAwHjlOaeQVbB5OlmF2.N', 'accept-ranges': 'bytes', 'content-type': 'binary/octet-stream', 'server': 'AmazonS3', 'content-length': '262735'}, 'RetryAttempts': 0}, 'AcceptRanges': 'bytes', 'LastModified': datetime.datetime(2023, 4, 2, 3, 42, 49, tzinfo=tzutc()), 'ContentLength': 262735, 'ETag': '"cde1715b3cbc30cc963e7a1c03c06554"', 'VersionId': 'KdRWpuBAP2gIAwHjlOaeQVbB5OlmF2.N', 'ContentType': 'binary/octet-stream', 'ServerSideEncryption': 'AES256', 'Metadata': {}, 'Body': <botocore.response.StreamingBody object at 0xffff6f795e50>}
[2023-04-02T03:43:00.757+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_dag.py", line 68, in upload_to_mongo_db
    coll.insert_many(s3_object)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_many
    raise TypeError("documents must be a non-empty list")
TypeError: documents must be a non-empty list
[2023-04-02T03:43:00.769+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=demo_dag, task_id=upload_to_mongo_db, execution_date=20230402T034255, start_date=20230402T034259, end_date=20230402T034300
[2023-04-02T03:43:00.780+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 428 for task upload_to_mongo_db (documents must be a non-empty list; 1550)
[2023-04-02T03:43:00.840+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-02T03:43:00.891+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
